sudo: required

language: minimal

addons:
  apt:
    packages:
      - snapd
    update: true
services:
  - docker

# Environment variables
env:
# EKS
  - NODES_SIZE=2
  - REGION=eu-west-1
# GKE

before_install:
  # install needed tooling: Terraform
  - export PATH=/snap/bin:$PATH
  - sudo snap install terraform
  - terraform --version
  - sudo snap install helm --classic
  
install:
  # install AWS EKS Cluster with Terraform

  - terraform init terraform-resources/aws/eks
  - terraform apply terraform-resources/aws/eks

  # install the openFaaS-cli
  - curl -sSL https://cli.openfaas.com | sudo sh


      #script: terraform --version
    # installing faas-cli
  #- curl -sSL https://cli.openfaas.com | sudo sh

# EKS OpenFaaS installation
# install eksctl for creating EKS cluster

  