sudo: required

language: minimal

services:
  - docker

# Environment variables
env:
# EKS
  - NODES_SIZE=2
  - REGION=eu-west-1
# GKE

before_install:
  - sudo apt-get update
  - 


# stages of CI/CD pipeline
stages:
  - prepare_tooling
  - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip &&
    unzip terraform_0.11.10_linux_amd64.zip &&
    mv terraform /usr/local/bin/
  - terraform --version

      #script: terraform --version
    # installing faas-cli
  #- curl -sSL https://cli.openfaas.com | sudo sh

# EKS OpenFaaS installation
# install eksctl for creating EKS cluster

  