sudo: required

language: minimal

services:
  - docker

# Environment variables
env:
# EKS
  - NODES_SIZE=2
  - REGION=eu-west-1
# GKE

# stages of CI/CD pipeline
stages:
  - prepare_tooling

jobs:
  include:
    - stage: prepare_tooling
      script: "Preparing needed tooling ... "
      script: sudo apt-get update
      script: "Installing Terraform 0.11.11 ..."
      script: sudo apt-get install unzip |
              wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip | 
              unzip terraform_0.11.10_linux_amd64.zip | 
              sudo mv terraform /usr/local/bin/
      script: terraform --version
    # installing faas-cli
  #- curl -sSL https://cli.openfaas.com | sudo sh

# EKS OpenFaaS installation
# install eksctl for creating EKS cluster

  