dist: xenial
sudo: required
language: minimal

addons:
  apt:
    update: false
  snaps:
    # - terraform
    - name: kubectl
      classic: true
    - name: helm
      classic: true
services:
  - docker

before_install:
  - ./scripts/openfaas-kind.sh
install:
  
script:

after_failure:
  # actions.. 
after_success:
  - echo BUILD SUCCESS <3
