sudo: required

language: minimal

services:
  - docker

# Environment variables
env:
# EKS
  - NODES_SIZE=2
  - REGION=eu-west-1
# GKE

# install needed tools
prepare_tooling:
  - echo APT-GET UPDATE Step ...
  - sudo apt-get update
  - echo installing Terraform 0.11.11 ...
  - curl https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip && unzip terraform_0.11.11_linux_amd64.zip
    # installing faas-cli
  #- curl -sSL https://cli.openfaas.com | sudo sh

# EKS OpenFaaS installation
# install eksctl for creating EKS cluster

  