dist: xenial
sudo: required
language: minimal

# safelist
branches:
  only:
  - master
  - develop

addons:
  apt:
    update: false
  snaps:
  #   # - terraform
    # install kubectl for interacting K8s
    - name: kubectl
      classic: true
    # install helm the package manager for K8s
    - name: helm
      classic: true
services:
  # install required docker service
  - docker

before_install:
  # install the faas-cli
  - curl -sSL https://cli.openfaas.com | sudo sh
install:
  # install temporary testing K8s Environment with KinD
  - ./scripts/installation/openfaas-kind.sh
script:
  # Build and unit tests
  - ./scripts/functions/weather-forecast.sh
# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#     echo "$DOCKER_PW" | docker login -u "$DOCKER_USERNAME" --password-stdin
#     faas-cli push -f testing/weather-forecast.yml
#     fi
# this will be executed when a pull request is merged into the master branch
deploy:
  - provider: script
    script: scripts/deploy_production.sh
    on:
      branch: master
  - provider: script
    script: scripts/deploy_staging.sh
    on:
      branch: develop
