sudo: required

language: minimal

addons:
  apt:
    packages:
      - snapd
    update: true
services:
  - docker

# Environment variables
env:
# EKS
  - NODES_SIZE=2
  - REGION=eu-west-1
# GKE

before_install:
  # install needed tooling: Terraform
  - export PATH=/snap/bin:$PATH
  - sudo snap install terraform
  - terraform --version
  
install:
  - curl -sSL https://cli.openfaas.com | sudo sh



      #script: terraform --version
    # installing faas-cli
  #- curl -sSL https://cli.openfaas.com | sudo sh

# EKS OpenFaaS installation
# install eksctl for creating EKS cluster

  